In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect("data/ledger.db")
# Fetch {name: id} pairs from categories table
ledger = pd.read_sql("SELECT * FROM ledger where amount = -2560 order by transaction_date DESC, amount ASC limit 100", conn)

In [3]:
ledger.shape

(1, 16)

In [4]:
ledger.head(10)

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7888,2026-04-28,Check #975014,-2560.0,Debit,975014,125994.88,125900.98,Import,0,Winter gyms,None,9,10,2,2026-05-25 15:29:09

In [8]:

# Fetch example script from site
script = pd.read_sql("""
            SELECT daily_posted_balance 
            FROM ledger 
            WHERE transaction_date != 'pending'
            ORDER BY transaction_date DESC, amount ASC 
            LIMIT 1
        """, conn)
script

   daily_posted_balance
0              85074.56

In [9]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM ledger l
            --where is_deleted = 0
            order by transaction_date desc
            limit 20
        """, conn)
sample

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7608,pending,NaN,0.00,Debit,NaN,78064.95,78064.95,Import,0,Evan still pending deets,"no response, board elected to move on, prior g...",12,9,3,2026-05-25 15:29:09
1,7903,pending,NaN,-1500.00,NaN,NaN,116304.85,116304.85,Import,1,TD Honararia,NaN,19,10,3,2026-05-25 15:29:09
2,7904,pending,NaN,-381.75,NaN,NaN,115923.10,115923.10,Import,1,MS Background Checks,NaN,12,10,5,2026-05-25 15:29:09
3,7905,pending,NaN,-4545.00,NaN,NaN,111378.10,111378.10,Import,1,,,9,10,6,2026-05-25 15:29:09
4,7906,pending,PayPal,-700.00,debit,NaN,NaN,NaN,Manual,0,Coach Jackson,,12,10,3,2026-05-30 19:38:45
5,7912,pending,HB to Nationals,-4138.00,debit,NaN,NaN,NaN,Manual,1,Donation from Board,,15,10,3,2026-05-31 13:02:42
6,7918,pending,Venmo,-200.00,debit,NaN,NaN,NaN,Manual,0,Driving to Spring Fling,,11,10,3,2026-06-19 21:14:11
7,7916,2026-06-15,PAYMENT VENMO *********6791 INTERNET PAYMENT,-79.00,debit,NaN,NaN,NaN,Bank,0,USAU Certs,,12,10,3,2026-06-19 20:57:08
8,7917,2026-06-15,INST XFER PAYPAL TOM.DIVINCENZO INTERNET PAYMENT,-30.00,debit,NaN,NaN,NaN,Bank,0,USAU Chaperone Expense,,12,10,5,2026-06-19 20:57:08
9,7915,2026-06-11,Check #975015,-4545.00,debit,975015,NaN,NaN,Bank,0,NaN,NaN,9,10,6,2026-06-19 20:57:08
10,7914,2026-06-08,Check #975016,-226.00,debit,975016,NaN,NaN,Bank,0,Spring Fling,,17,10,3,2026-06-19 20:57:08
11,7913,2026-05-31,Brian Butler PAYMENT ID BBT395806773 ZELLE BUS...,-4138.00,debit,NaN,NaN,NaN,Bank,0,Donation from Board,NaN,15,10,3,2026-06-19 20:57:08
12,7910,2026-05-26,INST XFER PAYPAL WABARTENSTEIN INTERNET PAYMENT,-1500.00,debit,NaN,NaN,NaN,Bank,0,TD Honararia,NaN,19,10,3,2026-05-30 19:40:57
13,7911,2026-05-25,ONLINE TO ****5539 - TRUIST ONLINE CREDIT CARD...,-38.25,debit,NaN,NaN,NaN,Bank,0,Mailchimp,,15,10,7,2026-05-30 19:40:57
14,7909,2026-05-21,SERVICE CHARGES - PRIOR PERIOD,-5.49,debit,NaN,NaN,NaN,Bank,0,Fee for Zelle Use,"Evidently, we get charged 1% of incoming Zelle...",15,10,7,2026-05-30 19:40:57
15,7907,2026-05-14,Check #975011,-400.00,debit,975011,NaN,NaN,Bank,0,Trophy for BSC Arlington,,20,10,10,2026-05-30 19:40:57
16,7908,2026-05-13,ONLINE TO ****3878 - TRUIST ONLINE CREDIT CARD...,-381.75,debit,NaN,NaN,NaN,Bank,0,MS Background Checks,NaN,12,10,5,2026-05-30 19:40:57
17,7898,2026-05-11,INST XFER PAYPAL AMYROAD INTERNET PAYMENT,-75.00,Debit,NaN,117804.85,118056.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
18,7899,2026-05-11,PAYMENT VENMO *********5573 INTERNET PAYMENT,-100.00,Debit,NaN,117804.85,117956.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
19,7900,2026-05-11,INST XFER PAYPAL HIIKH INTERNET PAYMENT,-75.00,Debit,NaN,117804.85,117881.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09

In [11]:
conn.execute('update ledger set is_deleted = 0 where id in (7903, 7905, 7912)')

In [12]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM ledger l
            --where is_deleted = 0
            order by transaction_date desc
            limit 20
        """, conn)
sample

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7608,pending,NaN,0.00,Debit,NaN,78064.95,78064.95,Import,0,Evan still pending deets,"no response, board elected to move on, prior g...",12,9,3,2026-05-25 15:29:09
1,7903,pending,NaN,-1500.00,NaN,NaN,116304.85,116304.85,Import,0,TD Honararia,NaN,19,10,3,2026-05-25 15:29:09
2,7904,pending,NaN,-381.75,NaN,NaN,115923.10,115923.10,Import,1,MS Background Checks,NaN,12,10,5,2026-05-25 15:29:09
3,7905,pending,NaN,-4545.00,NaN,NaN,111378.10,111378.10,Import,0,,,9,10,6,2026-05-25 15:29:09
4,7906,pending,PayPal,-700.00,debit,NaN,NaN,NaN,Manual,0,Coach Jackson,,12,10,3,2026-05-30 19:38:45
5,7912,pending,HB to Nationals,-4138.00,debit,NaN,NaN,NaN,Manual,0,Donation from Board,,15,10,3,2026-05-31 13:02:42
6,7918,pending,Venmo,-200.00,debit,NaN,NaN,NaN,Manual,0,Driving to Spring Fling,,11,10,3,2026-06-19 21:14:11
7,7916,2026-06-15,PAYMENT VENMO *********6791 INTERNET PAYMENT,-79.00,debit,NaN,NaN,NaN,Bank,0,USAU Certs,,12,10,3,2026-06-19 20:57:08
8,7917,2026-06-15,INST XFER PAYPAL TOM.DIVINCENZO INTERNET PAYMENT,-30.00,debit,NaN,NaN,NaN,Bank,0,USAU Chaperone Expense,,12,10,5,2026-06-19 20:57:08
9,7915,2026-06-11,Check #975015,-4545.00,debit,975015,NaN,NaN,Bank,0,NaN,NaN,9,10,6,2026-06-19 20:57:08
10,7914,2026-06-08,Check #975016,-226.00,debit,975016,NaN,NaN,Bank,0,Spring Fling,,17,10,3,2026-06-19 20:57:08
11,7913,2026-05-31,Brian Butler PAYMENT ID BBT395806773 ZELLE BUS...,-4138.00,debit,NaN,NaN,NaN,Bank,0,Donation from Board,NaN,15,10,3,2026-06-19 20:57:08
12,7910,2026-05-26,INST XFER PAYPAL WABARTENSTEIN INTERNET PAYMENT,-1500.00,debit,NaN,NaN,NaN,Bank,0,TD Honararia,NaN,19,10,3,2026-05-30 19:40:57
13,7911,2026-05-25,ONLINE TO ****5539 - TRUIST ONLINE CREDIT CARD...,-38.25,debit,NaN,NaN,NaN,Bank,0,Mailchimp,,15,10,7,2026-05-30 19:40:57
14,7909,2026-05-21,SERVICE CHARGES - PRIOR PERIOD,-5.49,debit,NaN,NaN,NaN,Bank,0,Fee for Zelle Use,"Evidently, we get charged 1% of incoming Zelle...",15,10,7,2026-05-30 19:40:57
15,7907,2026-05-14,Check #975011,-400.00,debit,975011,NaN,NaN,Bank,0,Trophy for BSC Arlington,,20,10,10,2026-05-30 19:40:57
16,7908,2026-05-13,ONLINE TO ****3878 - TRUIST ONLINE CREDIT CARD...,-381.75,debit,NaN,NaN,NaN,Bank,0,MS Background Checks,NaN,12,10,5,2026-05-30 19:40:57
17,7898,2026-05-11,INST XFER PAYPAL AMYROAD INTERNET PAYMENT,-75.00,Debit,NaN,117804.85,118056.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
18,7899,2026-05-11,PAYMENT VENMO *********5573 INTERNET PAYMENT,-100.00,Debit,NaN,117804.85,117956.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
19,7900,2026-05-11,INST XFER PAYPAL HIIKH INTERNET PAYMENT,-75.00,Debit,NaN,117804.85,117881.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09

In [13]:
conn.execute('delete from ledger where id in (7916, 7917, 7915, 7914, 7913, 7910, 7911, 7909, 7907, 7908)')

In [14]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM ledger l
            --where is_deleted = 0
            order by transaction_date desc
            limit 20
        """, conn)
sample

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7608,pending,NaN,0.00,Debit,None,78064.95,78064.95,Import,0,Evan still pending deets,"no response, board elected to move on, prior g...",12,9,3,2026-05-25 15:29:09
1,7903,pending,NaN,-1500.00,NaN,None,116304.85,116304.85,Import,0,TD Honararia,NaN,19,10,3,2026-05-25 15:29:09
2,7904,pending,NaN,-381.75,NaN,None,115923.10,115923.10,Import,1,MS Background Checks,NaN,12,10,5,2026-05-25 15:29:09
3,7905,pending,NaN,-4545.00,NaN,None,111378.10,111378.10,Import,0,,,9,10,6,2026-05-25 15:29:09
4,7906,pending,PayPal,-700.00,debit,None,NaN,NaN,Manual,0,Coach Jackson,,12,10,3,2026-05-30 19:38:45
5,7912,pending,HB to Nationals,-4138.00,debit,None,NaN,NaN,Manual,0,Donation from Board,,15,10,3,2026-05-31 13:02:42
6,7918,pending,Venmo,-200.00,debit,None,NaN,NaN,Manual,0,Driving to Spring Fling,,11,10,3,2026-06-19 21:14:11
7,7898,2026-05-11,INST XFER PAYPAL AMYROAD INTERNET PAYMENT,-75.00,Debit,None,117804.85,118056.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
8,7899,2026-05-11,PAYMENT VENMO *********5573 INTERNET PAYMENT,-100.00,Debit,None,117804.85,117956.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
9,7900,2026-05-11,INST XFER PAYPAL HIIKH INTERNET PAYMENT,-75.00,Debit,None,117804.85,117881.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
10,7901,2026-05-11,PAYMENT VENMO *********1318 INTERNET PAYMENT,-50.00,Debit,None,117804.85,117831.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
11,7902,2026-05-11,PAYMENT VENMO *********9961 INTERNET PAYMENT,-27.00,Debit,None,117804.85,117804.85,Import,0,USAU Certs,NaN,12,10,10,2026-05-25 15:29:09
12,7897,2026-05-04,PAYMENT VENMO *********1259 INTERNET PAYMENT,-61.00,Debit,None,118131.85,118131.85,Import,0,USAU Certs,NaN,12,10,10,2026-05-25 15:29:09
13,7895,2026-05-01,MOBILE TO ****5539 - TRUIST ONLINE CREDIT CARD...,-7778.00,Debit,None,118192.85,118242.85,Import,0,Spring Fling,NaN,13,10,3,2026-05-25 15:29:09
14,7896,2026-05-01,PAYMENT VENMO *********2426 INTERNET PAYMENT,-50.00,Debit,None,118192.85,118192.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
15,7892,2026-04-30,PAYMENT VENMO *********9022 INTERNET PAYMENT,-239.36,Debit,None,126020.85,126155.00,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
16,7893,2026-04-30,PAYMENT VENMO *********6466 INTERNET PAYMENT,-200.00,Debit,None,126020.85,125955.00,Import,0,Spring Fling Coach Driving,NaN,12,10,3,2026-05-25 15:29:09
17,7894,2026-04-30,TopScore YULA-VA MAIN ACCOUNT ACH CREDIT,65.85,Credit,None,126020.85,126020.85,Import,0,Bulk Reconciled - TopScore,,3,10,7,2026-05-25 15:29:09
18,7890,2026-04-29,Trina Alcorn PAYMENT ID BBT387866829 ZELLE BUS...,-121.69,Debit,None,126394.36,125873.19,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
19,7891,2026-04-29,TopScore YULA-VA MAIN ACCOUNT ACH CREDIT,521.17,Credit,None,126394.36,126394.36,Import,0,Bulk Reconciled - TopScore,,3,10,7,2026-05-25 15:29:09

In [21]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT 
                p.name as program_name,
                c.flow as flow,
                SUM(l.amount * ifnull(ar.percentage,0)) as total
            FROM ledger l
            left join allocation_methods am on l.allocation_method_id = am.id
            left join allocation_rules ar on am.id = ar.method_id
            left JOIN programs p ON ar.program_id = p.id
            left JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = 7
            GROUP BY p.name, c.flow
            union all
            SELECT 
                'Total' as program_name,
                c.flow as flow,
                SUM(l.amount) as total
            FROM ledger l
            left JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = 7
            GROUP BY c.flow
            
        """, conn)
sample

  program_name     flow      total
0         None  Expense       0.00
1         None   Income       0.00
2        Total  Expense -128821.93
3        Total   Income  122259.96

In [22]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM allocation_methods
            limit 10
        """, conn)
sample

,id,name,description
0,1,High School Fall,Direct entirely High School Fall
1,2,High School Winter,Direct entirely High School Winter
2,3,High School Spring,Direct entirely High School Spring
3,4,Middle School Fall,Direct entirely Middle School Fall
4,5,Middle School Spring,Direct entirely Middle School Spring
5,6,2026 Player Distribution,Split based on the distribution of players in ...
6,7,2026 Registration Distribution,Split based on the distribution of registratio...
7,8,2025 Player Distribution,Split based on the distribution of players in ...
8,9,2025 Registration Distribution,Split based on the distribution of registratio...

In [ ]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM topscore_
            limit 10
        """, conn)
sample