In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect("data/ledger.db")
# Fetch {name: id} pairs from categories table

In [4]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM sqlite_master
            where type in ('table', 'view')
            order by name
        """, conn)
sample

,type,name,tbl_name,rootpage,sql
0,table,allocation_methods,allocation_methods,13,CREATE TABLE allocation_methods (\n ...
1,table,allocation_rules,allocation_rules,16,CREATE TABLE allocation_rules (\n ...
2,table,categories,categories,5,CREATE TABLE categories (\n ...
3,table,fy,fy,4,CREATE TABLE fy (\n fiscal_...
4,table,import_staging,import_staging,8,CREATE TABLE import_staging (\n ...
5,table,ledger,ledger,9,CREATE TABLE ledger (\n id ...
6,view,ledger_balance_view,ledger_balance_view,0,CREATE VIEW ledger_balance_view AS\n ...
7,table,programs,programs,2,CREATE TABLE programs (\n id IN...
8,table,registration_allocation_methods,registration_allocation_methods,2656,CREATE TABLE registration_allocation_methods (...
9,table,registration_groupings,registration_groupings,5723,CREATE TABLE registration_groupings (\n ...
10,table,sqlite_sequence,sqlite_sequence,7,"CREATE TABLE sqlite_sequence(name,seq)"
11,table,topscore_product_mappings,topscore_product_mappings,5725,CREATE TABLE topscore_product_mappings (\n ...
12,table,topscore_transfer_items,topscore_transfer_items,119,CREATE TABLE topscore_transfer_items (\n ...
13,table,transactions,transactions,3,CREATE TABLE transactions (\n i...

In [6]:
ledger = pd.read_sql("SELECT * FROM ledger where amount = -2560 order by transaction_date DESC, amount ASC limit 100", conn)
ledger.shape

(1, 16)

In [7]:
ledger.head(10)

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7888,2026-04-28,Check #975014,-2560.0,Debit,975014,125994.88,125900.98,Import,0,Winter gyms,None,9,10,2,2026-05-25 15:29:09

In [18]:

# Fetch example script from site
script = pd.read_sql("""
            SELECT transaction_date, source_indicator, count(*) 
            FROM ledger
            where is_deleted = 0
            GROUP BY transaction_date, source_indicator
            ORDER BY transaction_date DESC 
            LIMIT 10
        """, conn)
script

  transaction_date source_indicator  count(*)
0          pending           Import         1
1       2026-07-06             Bank         3
2       2026-07-03             Bank         1
3       2026-06-29             Bank         1
4       2026-06-28             Bank         2
5       2026-06-26             Bank         3
6       2026-06-25             Bank         2
7       2026-06-24             Bank         9
8       2026-06-23             Bank         2
9       2026-06-15             Bank         2

(1, 16)

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7888,2026-04-28,Check #975014,-2560.0,Debit,975014,125994.88,125900.98,Import,0,Winter gyms,None,9,10,2,2026-05-25 15:29:09

In [8]:

# Fetch example script from site
script = pd.read_sql("""
            SELECT daily_posted_balance 
            FROM ledger 
            WHERE transaction_date != 'pending'
            ORDER BY transaction_date DESC, amount ASC 
            LIMIT 1
        """, conn)
script

   daily_posted_balance
0              85074.56

In [5]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM ledger l
            --where is_deleted = 0
            order by transaction_date desc
            limit 20
        """, conn)
sample

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7608,pending,None,0.00,Debit,None,78064.95,None,Import,0,Evan still pending deets,"no response, board elected to move on, prior g...",12,9,3,2026-05-25 15:29:09
1,7903,pending,None,-1500.00,None,None,116304.85,None,Import,1,TD Honararia,None,19,10,3,2026-05-25 15:29:09
2,7904,pending,None,-381.75,None,None,115923.10,None,Import,1,MS Background Checks,None,12,10,5,2026-05-25 15:29:09
3,7905,pending,None,-4545.00,None,None,111378.10,None,Import,1,,,9,10,6,2026-05-25 15:29:09
4,7906,pending,PayPal,-700.00,debit,nan,NaN,None,Manual,1,Coach Jackson,Revised amount was paid with the rest of the c...,12,10,3,2026-05-30 19:38:45
5,7912,pending,HB to Nationals,-4138.00,debit,None,NaN,None,Manual,1,Donation from Board,,15,10,3,2026-05-31 13:02:42
6,7918,pending,Venmo,-200.00,debit,nan,NaN,None,Manual,1,Driving to Spring Fling,Merged with USAU fees into 1 payment,11,10,3,2026-06-19 21:14:11
7,7929,pending,Zelle Beau D,-2440.00,debit,None,NaN,None,Manual,1,,,12,10,3,2026-06-24 01:32:35
8,7930,pending,Venmo Thomas Callen,-2270.00,debit,None,NaN,None,Manual,1,Bulk Reconciled - Venmo,,12,10,3,2026-06-24 01:34:02
9,7931,pending,Venmo Michael Lesmez,-2030.00,debit,None,NaN,None,Manual,1,Bulk Reconciled - Venmo,,12,10,3,2026-06-24 01:35:31
10,7932,pending,Venmo Tyler Byrum,-2040.00,debit,nan,NaN,None,Manual,1,Bulk Reconciled - Venmo,"typo in amount, corrected on bank statement im...",12,10,3,2026-06-24 01:36:23
11,7933,pending,PayPal Maddy Boyle,-2520.00,debit,None,NaN,None,Manual,1,,,12,10,3,2026-06-24 01:36:54
12,7934,pending,Zelle Catalina,-2270.00,debit,None,NaN,None,Manual,1,,,12,10,3,2026-06-24 01:37:28
13,7935,pending,Paypal Elise Jackson,-1047.50,debit,None,NaN,None,Manual,1,,,12,10,3,2026-06-24 01:38:02
14,7936,pending,Zelle Andrew London,-1350.00,debit,None,NaN,None,Manual,1,,,12,10,3,2026-06-24 01:38:37
15,7937,pending,Venmo Ellie Heil,-2640.00,debit,None,NaN,None,Manual,1,Bulk Reconciled - Venmo,,12,10,3,2026-06-24 01:39:26
16,7938,pending,Venmo Tyler Monroe,-2320.00,debit,None,NaN,None,Manual,1,Bulk Reconciled - Venmo,,12,10,3,2026-06-24 01:39:55
17,7939,pending,Venmo Zach Norbaum,-2520.00,debit,None,NaN,None,Manual,1,Bulk Reconciled - Venmo,,12,10,3,2026-06-24 01:40:26
18,7940,pending,Venmo Austin Alvarado,-1870.00,debit,None,NaN,None,Manual,1,Bulk Reconciled - Venmo,,12,10,3,2026-06-24 01:41:02
19,7941,pending,Venmo Sydney Rehder,-2207.50,debit,None,NaN,None,Manual,1,Bulk Reconciled - Venmo,,12,10,3,2026-06-24 01:41:32

In [11]:
conn.execute('update ledger set is_deleted = 0 where id in (7903, 7905, 7912)')

In [12]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM ledger l
            --where is_deleted = 0
            order by transaction_date desc
            limit 20
        """, conn)
sample

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7608,pending,NaN,0.00,Debit,NaN,78064.95,78064.95,Import,0,Evan still pending deets,"no response, board elected to move on, prior g...",12,9,3,2026-05-25 15:29:09
1,7903,pending,NaN,-1500.00,NaN,NaN,116304.85,116304.85,Import,0,TD Honararia,NaN,19,10,3,2026-05-25 15:29:09
2,7904,pending,NaN,-381.75,NaN,NaN,115923.10,115923.10,Import,1,MS Background Checks,NaN,12,10,5,2026-05-25 15:29:09
3,7905,pending,NaN,-4545.00,NaN,NaN,111378.10,111378.10,Import,0,,,9,10,6,2026-05-25 15:29:09
4,7906,pending,PayPal,-700.00,debit,NaN,NaN,NaN,Manual,0,Coach Jackson,,12,10,3,2026-05-30 19:38:45
5,7912,pending,HB to Nationals,-4138.00,debit,NaN,NaN,NaN,Manual,0,Donation from Board,,15,10,3,2026-05-31 13:02:42
6,7918,pending,Venmo,-200.00,debit,NaN,NaN,NaN,Manual,0,Driving to Spring Fling,,11,10,3,2026-06-19 21:14:11
7,7916,2026-06-15,PAYMENT VENMO *********6791 INTERNET PAYMENT,-79.00,debit,NaN,NaN,NaN,Bank,0,USAU Certs,,12,10,3,2026-06-19 20:57:08
8,7917,2026-06-15,INST XFER PAYPAL TOM.DIVINCENZO INTERNET PAYMENT,-30.00,debit,NaN,NaN,NaN,Bank,0,USAU Chaperone Expense,,12,10,5,2026-06-19 20:57:08
9,7915,2026-06-11,Check #975015,-4545.00,debit,975015,NaN,NaN,Bank,0,NaN,NaN,9,10,6,2026-06-19 20:57:08
10,7914,2026-06-08,Check #975016,-226.00,debit,975016,NaN,NaN,Bank,0,Spring Fling,,17,10,3,2026-06-19 20:57:08
11,7913,2026-05-31,Brian Butler PAYMENT ID BBT395806773 ZELLE BUS...,-4138.00,debit,NaN,NaN,NaN,Bank,0,Donation from Board,NaN,15,10,3,2026-06-19 20:57:08
12,7910,2026-05-26,INST XFER PAYPAL WABARTENSTEIN INTERNET PAYMENT,-1500.00,debit,NaN,NaN,NaN,Bank,0,TD Honararia,NaN,19,10,3,2026-05-30 19:40:57
13,7911,2026-05-25,ONLINE TO ****5539 - TRUIST ONLINE CREDIT CARD...,-38.25,debit,NaN,NaN,NaN,Bank,0,Mailchimp,,15,10,7,2026-05-30 19:40:57
14,7909,2026-05-21,SERVICE CHARGES - PRIOR PERIOD,-5.49,debit,NaN,NaN,NaN,Bank,0,Fee for Zelle Use,"Evidently, we get charged 1% of incoming Zelle...",15,10,7,2026-05-30 19:40:57
15,7907,2026-05-14,Check #975011,-400.00,debit,975011,NaN,NaN,Bank,0,Trophy for BSC Arlington,,20,10,10,2026-05-30 19:40:57
16,7908,2026-05-13,ONLINE TO ****3878 - TRUIST ONLINE CREDIT CARD...,-381.75,debit,NaN,NaN,NaN,Bank,0,MS Background Checks,NaN,12,10,5,2026-05-30 19:40:57
17,7898,2026-05-11,INST XFER PAYPAL AMYROAD INTERNET PAYMENT,-75.00,Debit,NaN,117804.85,118056.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
18,7899,2026-05-11,PAYMENT VENMO *********5573 INTERNET PAYMENT,-100.00,Debit,NaN,117804.85,117956.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
19,7900,2026-05-11,INST XFER PAYPAL HIIKH INTERNET PAYMENT,-75.00,Debit,NaN,117804.85,117881.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09

In [13]:
#conn.execute('delete from ledger where id in (7916, 7917, 7915, 7914, 7913, 7910, 7911, 7909, 7907, 7908)')

In [14]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM ledger l
            --where is_deleted = 0
            order by transaction_date desc
            limit 20
        """, conn)
sample

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,7608,pending,NaN,0.00,Debit,None,78064.95,78064.95,Import,0,Evan still pending deets,"no response, board elected to move on, prior g...",12,9,3,2026-05-25 15:29:09
1,7903,pending,NaN,-1500.00,NaN,None,116304.85,116304.85,Import,0,TD Honararia,NaN,19,10,3,2026-05-25 15:29:09
2,7904,pending,NaN,-381.75,NaN,None,115923.10,115923.10,Import,1,MS Background Checks,NaN,12,10,5,2026-05-25 15:29:09
3,7905,pending,NaN,-4545.00,NaN,None,111378.10,111378.10,Import,0,,,9,10,6,2026-05-25 15:29:09
4,7906,pending,PayPal,-700.00,debit,None,NaN,NaN,Manual,0,Coach Jackson,,12,10,3,2026-05-30 19:38:45
5,7912,pending,HB to Nationals,-4138.00,debit,None,NaN,NaN,Manual,0,Donation from Board,,15,10,3,2026-05-31 13:02:42
6,7918,pending,Venmo,-200.00,debit,None,NaN,NaN,Manual,0,Driving to Spring Fling,,11,10,3,2026-06-19 21:14:11
7,7898,2026-05-11,INST XFER PAYPAL AMYROAD INTERNET PAYMENT,-75.00,Debit,None,117804.85,118056.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
8,7899,2026-05-11,PAYMENT VENMO *********5573 INTERNET PAYMENT,-100.00,Debit,None,117804.85,117956.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
9,7900,2026-05-11,INST XFER PAYPAL HIIKH INTERNET PAYMENT,-75.00,Debit,None,117804.85,117881.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
10,7901,2026-05-11,PAYMENT VENMO *********1318 INTERNET PAYMENT,-50.00,Debit,None,117804.85,117831.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
11,7902,2026-05-11,PAYMENT VENMO *********9961 INTERNET PAYMENT,-27.00,Debit,None,117804.85,117804.85,Import,0,USAU Certs,NaN,12,10,10,2026-05-25 15:29:09
12,7897,2026-05-04,PAYMENT VENMO *********1259 INTERNET PAYMENT,-61.00,Debit,None,118131.85,118131.85,Import,0,USAU Certs,NaN,12,10,10,2026-05-25 15:29:09
13,7895,2026-05-01,MOBILE TO ****5539 - TRUIST ONLINE CREDIT CARD...,-7778.00,Debit,None,118192.85,118242.85,Import,0,Spring Fling,NaN,13,10,3,2026-05-25 15:29:09
14,7896,2026-05-01,PAYMENT VENMO *********2426 INTERNET PAYMENT,-50.00,Debit,None,118192.85,118192.85,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
15,7892,2026-04-30,PAYMENT VENMO *********9022 INTERNET PAYMENT,-239.36,Debit,None,126020.85,126155.00,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
16,7893,2026-04-30,PAYMENT VENMO *********6466 INTERNET PAYMENT,-200.00,Debit,None,126020.85,125955.00,Import,0,Spring Fling Coach Driving,NaN,12,10,3,2026-05-25 15:29:09
17,7894,2026-04-30,TopScore YULA-VA MAIN ACCOUNT ACH CREDIT,65.85,Credit,None,126020.85,126020.85,Import,0,Bulk Reconciled - TopScore,,3,10,7,2026-05-25 15:29:09
18,7890,2026-04-29,Trina Alcorn PAYMENT ID BBT387866829 ZELLE BUS...,-121.69,Debit,None,126394.36,125873.19,Import,0,Spring Fling,NaN,17,10,3,2026-05-25 15:29:09
19,7891,2026-04-29,TopScore YULA-VA MAIN ACCOUNT ACH CREDIT,521.17,Credit,None,126394.36,126394.36,Import,0,Bulk Reconciled - TopScore,,3,10,7,2026-05-25 15:29:09

In [16]:
conn.commit()
#reimport bank file

In [ ]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM ledger l
            --where is_deleted = 0
            order by transaction_date desc
            limit 20
        """, conn)
sample

In [21]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT 
                p.name as program_name,
                c.flow as flow,
                SUM(l.amount * ifnull(ar.percentage,0)) as total
            FROM ledger l
            left join allocation_methods am on l.allocation_method_id = am.id
            left join allocation_rules ar on am.id = ar.method_id
            left JOIN programs p ON ar.program_id = p.id
            left JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = 7
            GROUP BY p.name, c.flow
            union all
            SELECT 
                'Total' as program_name,
                c.flow as flow,
                SUM(l.amount) as total
            FROM ledger l
            left JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = 7
            GROUP BY c.flow
            
        """, conn)
sample

  program_name     flow      total
0         None  Expense       0.00
1         None   Income       0.00
2        Total  Expense -128821.93
3        Total   Income  122259.96

In [22]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM allocation_methods
            limit 10
        """, conn)
sample

,id,name,description
0,1,High School Fall,Direct entirely High School Fall
1,2,High School Winter,Direct entirely High School Winter
2,3,High School Spring,Direct entirely High School Spring
3,4,Middle School Fall,Direct entirely Middle School Fall
4,5,Middle School Spring,Direct entirely Middle School Spring
5,6,2026 Player Distribution,Split based on the distribution of players in ...
6,7,2026 Registration Distribution,Split based on the distribution of registratio...
7,8,2025 Player Distribution,Split based on the distribution of players in ...
8,9,2025 Registration Distribution,Split based on the distribution of registratio...

In [5]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT count(*)
            FROM topscore_transfer_items
            limit 10
        """, conn)
sample

   count(*)
0     38112

In [6]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM topscore_transfer_items
            limit 10
        """, conn)
sample

,id,source_filename,source_row_number,transfer_timestamp,transfer_id,item_type,type,product_name,applied_currency,amount,identifier,imported_at
0,113335,transfers_export_2026-09-04_08_03_8nQT.csv,2,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,cc_fee,Payment,YULA Middle School League Fall 2017 Free Agent...,USD,-1.13,ch_1AxNKiDADMyYiMfMn0Q5Tz8r,2026-09-04 12:14:50
1,113336,transfers_export_2026-09-04_08_03_8nQT.csv,3,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,cc_fee,Payment,YULA Middle School League Fall 2017 Free Agent...,USD,-1.13,ch_1AxMYeDADMyYiMfMKiQqIVrs,2026-09-04 12:14:50
2,113337,transfers_export_2026-09-04_08_03_8nQT.csv,4,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,payment,Payment,YULA Middle School League Fall 2017 Free Agent...,USD,30.00,ch_1AxNKiDADMyYiMfMn0Q5Tz8r,2026-09-04 12:14:50
3,113338,transfers_export_2026-09-04_08_03_8nQT.csv,5,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,cc_fee,Payment,YULA Open Ultimate (YOU) - High School - Fall ...,USD,-2.29,ch_1AxFWhDADMyYiMfMaubuNnd8,2026-09-04 12:14:50
4,113339,transfers_export_2026-09-04_08_03_8nQT.csv,6,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,payment,Payment,YULA Middle School League Fall 2017 Free Agent...,USD,30.00,ch_1AxMYeDADMyYiMfMKiQqIVrs,2026-09-04 12:14:50
5,113340,transfers_export_2026-09-04_08_03_8nQT.csv,7,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,cc_fee,Payment,Donation to YULA,USD,-0.76,ch_1AxFWhDADMyYiMfMaubuNnd8,2026-09-04 12:14:50
6,113341,transfers_export_2026-09-04_08_03_8nQT.csv,8,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,payment,Payment,YULA Open Ultimate (YOU) - High School - Fall ...,USD,75.00,ch_1AxFWhDADMyYiMfMaubuNnd8,2026-09-04 12:14:50
7,113342,transfers_export_2026-09-04_08_03_8nQT.csv,9,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,network_fee,Payment,YULA Open Ultimate (YOU) - High School - Fall ...,USD,0.00,ch_1Ax4REDADMyYiMfMWUsqCOnC,2026-09-04 12:14:50
8,113343,transfers_export_2026-09-04_08_03_8nQT.csv,10,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,payment,Payment,YULA Open Ultimate (YOU) - High School - Fall ...,USD,75.00,ch_1Ax6YLDADMyYiMfMMoCX7bpi,2026-09-04 12:14:50
9,113344,transfers_export_2026-09-04_08_03_8nQT.csv,11,2017-09-12 06:07:02,po_1B1BIBIInv4bBpPNza9SFV55,topscore_fee,Payment,YULA Open Ultimate (YOU) - High School - Fall ...,USD,-2.25,ch_1Ax4REDADMyYiMfMWUsqCOnC,2026-09-04 12:14:50

In [10]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT source_filename, count(*)
            FROM topscore_transfer_items
            group by 1
            limit 10
        """, conn)
sample

                              source_filename  count(*)
0  transfers_export_2026-09-04_08_03_8nQT.csv     38112

In [7]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT count(*)
            FROM topscore_product_mappings
            limit 10
        """, conn)
sample

   count(*)
0       192

In [8]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT *
            FROM topscore_product_mappings
            limit 10
        """, conn)
sample

,product_name,grouping,primary_registration_ind
0,2024 Friendraiser at WHINO,Fundraising,0
1,$50 toward HB's HSNI expenses,Fundraising,0
2,A Team Upgrade (100% cost),High School,0
3,Add Middle School Sky Team (for experienced pl...,Middle School,0
4,April 21 Girl-Match Youth Clinic Individual Re...,Fundraising,0
5,AUA - YULA Middle School Ultimate Clinic Fall ...,Middle School,1
6,B to A Upgrade Fee,High School,0
7,Black Hoodie Large,Merchandise,0
8,Black Hoodie Small,Merchandise,0
9,Boys Aces,High School,0

In [69]:

# Fetch example script from site
sample = pd.read_sql("""
            SELECT substr(topscore_transfer_items.transfer_timestamp, 1, 4) as yr,
            strftime('%Y', date(topscore_transfer_items.transfer_timestamp, '+6 month', 'start of year')) as FY,
            case when topscore_product_mappings.grouping = 'Winter' then 'Winter'
              when strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06' then 'Fall' 
              else 'Spring' end as szn,
--            topscore_product_mappings.grouping, 
            count(distinct(topscore_transfer_items.product_name)) as prod_cnt,
            sum(case when topscore_transfer_items.item_type = 'payment' then 1 else 0 end) as reg_cnt,
            sum(case when topscore_transfer_items.item_type = 'payment'
                then topscore_product_mappings.primary_registration_ind else 0 end) as primary_cnt, 

            sum(topscore_transfer_items.amount) as sum_amt,
            count (*)
            FROM topscore_transfer_items
            left join topscore_product_mappings
            on topscore_transfer_items.product_name = topscore_product_mappings.product_name
            where substr(topscore_transfer_items.transfer_timestamp, 1, 4) > '2024'
            group by 1, 2,3
            order by 1, 2, 3
        """, conn)
sample

     yr    FY     szn  prod_cnt  reg_cnt  primary_cnt   sum_amt  count (*)
0  2025  2025  Spring        10      369          302  67795.27       1514
1  2025  2025  Winter         1       21           21   1284.82         84
2  2025  2026    Fall        11      378          196  31678.78       1562
3  2025  2026  Winter         1       31           31   2030.02        124
4  2026  2026  Spring        10      396          308  42274.76       1605
5  2026  2026  Winter         1       39           39   2453.41        156
6  2026  2027    Fall         8      167          113  14800.18        672

In [144]:

# Fetch example script from site
conn.execute("""drop view if exists program_registration_summary""")
conn.execute("""
create view program_registration_summary as
with yearly_summary as (
            select
            /* For transactions, the Fiscal Year is from July 1 -> Jun 30 */
            'FY'||strftime('%Y', date(topscore_transfer_items.transfer_timestamp, '+6 month', 'start of year')) as FY,
            
            /* Fall begins in July until December, Leverage the product mapping groupings
               Use the primary indicator (1 or 0) to avoid the add-on registrations 
               The identifier can have multiple player registrations in the same registration
               Each registrant has only 1 'payment' item type, and 3 other item types. */
               
            sum(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              and topscore_transfer_items.item_type = 'payment'
              then topscore_product_mappings.primary_registration_ind
              else 0 end) as hs_fall_players,
            sum(case 
              when topscore_product_mappings.grouping = 'Winter'
              and topscore_transfer_items.item_type = 'payment'
              then 1
              else 0 end) as winter_players,
            sum(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              and topscore_transfer_items.item_type = 'payment'
              then topscore_product_mappings.primary_registration_ind
              else 0 end) as hs_spring_players,
            sum(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              and topscore_transfer_items.item_type = 'payment'
              then topscore_product_mappings.primary_registration_ind
              else 0 end) as ms_fall_players,
            sum(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              and topscore_transfer_items.item_type = 'payment'
              then topscore_product_mappings.primary_registration_ind
              else 0 end) as ms_spring_players,

            sum(case 
              when topscore_transfer_items.item_type = 'payment'
              and topscore_product_mappings.grouping in ('High School', 'Winter', 'Middle School') 
              then topscore_product_mappings.primary_registration_ind
              else 0 end 
              ) as total_players,
              
            sum(case 
                when item_type = 'payment'
                and topscore_product_mappings.grouping in ('High School', 'Winter', 'Middle School')
                then 1
              else 0 end) as program_registrations,


            /* For income, use total, not just primary registrations */
            sum(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              then topscore_transfer_items.amount
              else 0 end) as hs_fall_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'Winter' then topscore_transfer_items.amount
              else 0 end) as winter_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              then topscore_transfer_items.amount
              else 0 end) as hs_spring_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              then topscore_transfer_items.amount
              else 0 end) as ms_fall_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              then topscore_transfer_items.amount
              else 0 end) as ms_spring_dollars,
        
            sum(case 
              when topscore_product_mappings.grouping in ('High School', 'Winter', 'Middle School') 
              then topscore_transfer_items.amount
              else 0 end) as program_dollars,

            /* Summary income metrics */
            sum(case when item_type = 'payment'
              then topscore_transfer_items.amount else 0 end) as gross_amt,
            sum(case when item_type = 'cc_fee'
              then topscore_transfer_items.amount else 0 end) as credit_card_fees,
            sum(case when item_type = 'network_fee'
              then topscore_transfer_items.amount else 0 end) as network_fees,
            sum(case when item_type = 'topscore_fee'
              then topscore_transfer_items.amount else 0 end) as topscore_fees,
            sum(topscore_transfer_items.amount) as net_amt,
            count (*) as accounting_records
            from topscore_transfer_items
            left join topscore_product_mappings
            on topscore_transfer_items.product_name = topscore_product_mappings.product_name
            group by 1
            order by 1
)
select 
/* player percentages */
    hs_fall_players / cast(total_players as real) as hs_fall_player_pct,
    winter_players / cast(total_players as real) as winter_player_pct,
    hs_spring_players / cast(total_players as real) as hs_spring_player_pct,
    ms_fall_players / cast(total_players as real) as ms_fall_player_pct,
    ms_spring_players / cast(total_players as real) as ms_spring_player_pct,
/* dollar percentages */
    hs_fall_dollars / cast(program_dollars as real) as hs_fall_dollar_pct,
    winter_dollars / cast(program_dollars as real) as winter_dollar_pct,
    hs_spring_dollars / cast(program_dollars as real) as hs_spring_dollar_pct,
    ms_fall_dollars / cast(program_dollars as real) as ms_fall_dollar_pct,
    ms_spring_dollars / cast(program_dollars as real) as ms_spring_dollar_pct,
    *
from yearly_summary
        """)

In [145]:

# Fetch example script from site
sample = pd.read_sql("""
select fy, * from program_registration_summary
        """, conn)
sample

,FY,hs_fall_player_pct,winter_player_pct,hs_spring_player_pct,ms_fall_player_pct,ms_spring_player_pct,hs_fall_dollar_pct,winter_dollar_pct,hs_spring_dollar_pct,ms_fall_dollar_pct,...,hs_spring_dollars,ms_fall_dollars,ms_spring_dollars,program_dollars,gross_amt,credit_card_fees,network_fees,topscore_fees,net_amt,accounting_records
0,FY2018,0.209091,0.000000,0.340000,0.172727,0.278182,0.274864,0.000000,0.601187,0.035341,...,45482.13,2673.69,6703.56,75653.93,85325.00,-2064.34,0.0,-2441.34,79135.32,3653
1,FY2019,0.193182,0.085227,0.301136,0.149148,0.271307,0.280134,0.026505,0.560063,0.040803,...,47721.08,3476.71,7881.14,85206.58,99049.50,-2382.56,0.0,-2857.76,91180.43,4401
2,FY2020,0.256831,0.140255,0.273224,0.116576,0.213115,0.829405,0.099990,-0.002804,0.074583,...,-79.18,2105.71,-33.10,28233.22,75855.75,-916.15,0.0,-1075.13,33974.47,4741
3,FY2021,0.177871,0.173669,0.242297,0.102241,0.303922,0.136685,0.095454,0.528763,0.048082,...,22615.38,2056.50,8169.82,42770.39,57392.75,-1457.85,0.0,-1665.96,52660.44,4330
4,FY2022,0.204052,0.099855,0.312590,0.120116,0.263386,0.221614,0.016525,0.574506,0.047425,...,44859.21,3703.11,10926.11,78083.04,89484.25,-2229.98,0.0,-2645.01,83304.26,4951
5,FY2023,0.209048,0.095164,0.319813,0.096724,0.279251,0.261732,0.025281,0.484349,0.058385,...,42554.92,5129.68,14958.47,87860.02,99109.75,-2378.67,0.0,-2919.91,92041.17,4403
6,FY2024,0.197655,0.102178,0.340034,0.103853,0.256281,0.127612,0.041410,0.565386,0.086975,...,45447.43,6991.29,14357.78,80383.08,89360.50,-2140.39,0.0,-2642.47,83307.64,3578
7,FY2025,0.240678,0.122034,0.330508,0.125424,0.181356,0.262672,0.040349,0.530843,0.078587,...,57322.61,8486.19,9453.95,107984.18,119831.75,-3199.15,0.0,-3559.35,111893.25,3936
8,FY2026,0.207317,0.121951,0.315331,0.134146,0.221254,0.330618,0.059132,0.374889,0.080314,...,28424.55,6089.53,11755.85,75821.22,84413.50,-2289.77,0.0,-2496.76,78436.97,3447
9,FY2027,0.663717,0.000000,0.000000,0.336283,0.000000,0.761212,0.000000,0.000000,0.238788,...,0.00,3468.15,0.00,14523.95,15703.00,-431.73,0.0,-471.09,14800.18,672

In [159]:

# Fetch example script from site
sample = pd.read_sql("""
SELECT 
                p.name as program_name,
                CASE
                    WHEN lower(c.flow) = 'income' THEN 'Income'
                    WHEN lower(c.flow) = 'expense' THEN 'Expense'
                    WHEN l.amount >= 0 THEN 'Income'
                    ELSE 'Expense'
                END as flow,
                CASE 
                    WHEN (lower(c.flow) = 'expense' OR (c.flow IS NULL AND l.amount < 0)) 
                    THEN - SUM(l.amount * ifnull(ar.percentage,0))
                    ELSE SUM(l.amount * ifnull(ar.percentage,0)) 
                END as total
            FROM ledger l
            LEFT JOIN allocation_methods am ON l.allocation_method_id = am.id
            LEFT JOIN allocation_rules ar ON am.id = ar.method_id
            LEFT JOIN programs p ON ar.program_id = p.id
            LEFT JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = '5' AND l.is_deleted = 0
            GROUP BY p.name, flow
/*
            UNION ALL

            SELECT 
                'Total' as program_name,
                CASE
                    WHEN lower(c.flow) = 'income' THEN 'Income'
                    WHEN lower(c.flow) = 'expense' THEN 'Expense'
                    WHEN l.amount >= 0 THEN 'Income'
                    ELSE 'Expense'
                END as flow,
                CASE 
                    WHEN (lower(c.flow) = 'expense' OR (c.flow IS NULL AND l.amount < 0)) 
                    THEN - SUM(l.amount)
                    ELSE SUM(l.amount) 
                END as total
            FROM ledger l
            LEFT JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = '5' AND l.is_deleted = 0
            GROUP BY flow
    */
        """, conn)
sample

           program_name     flow         total
0                  None  Expense      0.000000
1                  None   Income      0.000000
2      High School Fall   Income   6693.233952
3    High School Spring  Expense   3001.000000
4    High School Spring   Income  29192.613202
5    High School Winter   Income   4674.239412
6    Middle School Fall   Income   2354.510915
7  Middle School Spring   Income   9353.722519

In [160]:

# Fetch example script from site
sample = pd.read_sql("""
SELECT 
                p.name as program_name,
                CASE
                    WHEN lower(c.flow) = 'income' THEN 'Income'
                    WHEN lower(c.flow) = 'expense' THEN 'Expense'
                    WHEN l.amount >= 0 THEN 'Income'
                    ELSE 'Expense'
                END as flow,
                CASE 
                    WHEN (lower(c.flow) = 'expense' OR (c.flow IS NULL AND l.amount < 0)) 
                    THEN - SUM(l.amount * ifnull(ar.percentage,0))
                    ELSE SUM(l.amount * ifnull(ar.percentage,0)) 
                END as total
            FROM ledger l
             
            LEFT JOIN allocation_rules ar ON  l.allocation_method_id = ar.method_id
            LEFT JOIN programs p ON ar.program_id = p.id
            LEFT JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = '5' AND l.is_deleted = 0
            GROUP BY p.name, flow
/*
            UNION ALL

            SELECT 
                'Total' as program_name,
                CASE
                    WHEN lower(c.flow) = 'income' THEN 'Income'
                    WHEN lower(c.flow) = 'expense' THEN 'Expense'
                    WHEN l.amount >= 0 THEN 'Income'
                    ELSE 'Expense'
                END as flow,
                CASE 
                    WHEN (lower(c.flow) = 'expense' OR (c.flow IS NULL AND l.amount < 0)) 
                    THEN - SUM(l.amount)
                    ELSE SUM(l.amount) 
                END as total
            FROM ledger l
            LEFT JOIN categories c ON l.category_id = c.id
            WHERE l.fiscal_year_id = '5' AND l.is_deleted = 0
            GROUP BY flow
    */
        """, conn)
sample

           program_name     flow         total
0                  None  Expense      0.000000
1                  None   Income      0.000000
2      High School Fall   Income   6693.233952
3    High School Spring  Expense   3001.000000
4    High School Spring   Income  29192.613202
5    High School Winter   Income   4674.239412
6    Middle School Fall   Income   2354.510915
7  Middle School Spring   Income   9353.722519

In [127]:
# Fetch example script from site
sample = pd.read_sql(""" SELECT  * FROM ledger l 
where transaction_date != 'pending' and is_Deleted = 0 order by transaction_date desc limit 5 """, conn)
sample

,id,transaction_date,description,amount,transaction_type,check_number,daily_posted_balance,running_balance,source_indicator,is_deleted,notes,more_notes,category_id,fiscal_year_id,allocation_method_id,created_at
0,8004,2026-09-03,TopScore YULA-VA MAIN ACCOUNT ACH CREDIT,75.30,credit,None,83241.14,83241.14,Bank,0,None,None,3,12,20,2026-09-04 12:12:59
1,8003,2026-09-02,TopScore YULA-VA MAIN ACCOUNT ACH CREDIT,588.21,credit,None,83165.84,83165.84,Bank,0,None,None,3,12,20,2026-09-04 12:12:59
2,8000,2026-08-28,MOBILE TO ****3878 - TRUIST ONLINE CREDIT CARD...,-6.59,debit,None,82577.63,82356.91,Bank,0,Topscore Charges,because they charge us when they don't get a c...,3,12,20,2026-08-30 16:18:40
3,8001,2026-08-28,MOBILE TO ****5539 - TRUIST ONLINE CREDIT CARD...,-38.25,debit,None,82577.63,82318.66,Bank,0,Mailchimp via credit card,,15,12,7,2026-08-30 16:18:40
4,8002,2026-08-28,TopScore YULA-VA MAIN ACCOUNT ACH CREDIT,258.97,credit,None,82577.63,82577.63,Bank,0,Bulk Reconciled - TopScore,,3,12,20,2026-08-30 16:18:40

In [128]:
# Fetch example script from site
sample = pd.read_sql(""" SELECT  * FROM allocation_methods """, conn)
sample

,id,name,description
0,1,High School Fall,Direct entirely High School Fall
1,2,High School Winter,Direct entirely High School Winter
2,3,High School Spring,Direct entirely High School Spring
3,4,Middle School Fall,Direct entirely Middle School Fall
4,5,Middle School Spring,Direct entirely Middle School Spring
5,6,2026 Player Distribution,Split based on the distribution of players in ...
6,7,2026 Registration Distribution,Split based on the distribution of registratio...
7,8,2025 Player Distribution,Split based on the distribution of players in ...
8,9,2025 Registration Distribution,Split based on the distribution of registratio...
9,10,High School Season Split,For proportional between the High School fall ...
10,11,Registration Distribution - 2018,Automatically calculated from TopScore registr...
11,12,Registration Distribution - 2019,Automatically calculated from TopScore registr...
12,13,Registration Distribution - 2020,Automatically calculated from TopScore registr...
13,14,Registration Distribution - 2021,Automatically calculated from TopScore registr...
14,15,Registration Distribution - 2022,Automatically calculated from TopScore registr...
15,16,Registration Distribution - 2023,Automatically calculated from TopScore registr...
16,17,Registration Distribution - 2024,Automatically calculated from TopScore registr...
17,18,Registration Distribution - 2025,Automatically calculated from TopScore registr...
18,19,Registration Distribution - 2026,Automatically calculated from TopScore registr...
19,20,Registration Distribution - 2027,Automatically calculated from TopScore registr...

In [131]:
# Fetch example script from site
sample = pd.read_sql(""" SELECT  * FROM allocation_rules where method_id in (1,2,3,4,5,6) """, conn)
sample

   id  method_id  program_id  percentage
0   1          1           1        1.00
1   2          2           2        1.00
2   3          3           3        1.00
3   4          4           5        1.00
4   5          5           6        1.00
5   6          6           1        0.21
6   7          6           2        0.12
7   8          6           3        0.32
8   9          6           5        0.13
9  10          6           6        0.22

In [132]:
# Fetch example script from site
sample = pd.read_sql(""" SELECT  * FROM fy  """, conn)
sample

    fiscal_year_id    name  start_date    end_date  active_ind
0                1  FY2017  2016-09-01  2017-08-31           0
1                2  FY2018  2017-09-01  2018-08-31           0
2                3  FY2019  2018-09-01  2019-08-31           0
3                4  FY2020  2019-09-01  2020-08-31           0
4                5  FY2021  2020-09-01  2021-08-31           0
5                6  FY2022  2021-09-01  2022-08-31           0
6                7  FY2023  2022-09-01  2023-08-31           0
7                8  FY2024  2023-09-01  2024-07-31           0
8                9  FY2025  2024-08-01  2025-07-31           0
9               10  FY2026  2025-08-01  2026-07-31           0
10              12  FY2027  2026-08-01  2027-07-31           1

In [147]:
# Fetch example script from site
sample = pd.read_sql(""" SELECT  * FROM programs  """, conn)
sample

,id,name,code,description,active_ind
0,1,High School Fall,HS01,Fall High School including ACES,1
1,2,High School Winter,HS02,"Winter High School Program, predominantly indoor",1
2,3,High School Spring,HS03,"Spring High School Program, including both A t...",1
3,5,Middle School Fall,MS01,"Fall Middle School Program, including skills a...",1
4,6,Middle School Spring,MS02,"Spring Middle School Program, including regula...",1

In [148]:
# ledger has Fiscal_Year_id, alllocation_method_id 
# FY has Fiscal_Year_id, name
# Fetch example script from site
sample = pd.read_sql(""" SELECT  fy.fiscal_year_id, fy.name,
 program_registration_summary.* 
FROM fy
left join program_registration_summary on fy.name = program_registration_summary.fy  """, conn)
sample

,fiscal_year_id,name,hs_fall_player_pct,winter_player_pct,hs_spring_player_pct,ms_fall_player_pct,ms_spring_player_pct,hs_fall_dollar_pct,winter_dollar_pct,hs_spring_dollar_pct,...,hs_spring_dollars,ms_fall_dollars,ms_spring_dollars,program_dollars,gross_amt,credit_card_fees,network_fees,topscore_fees,net_amt,accounting_records
0,1,FY2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,FY2018,0.209091,0.000000,0.340000,0.172727,0.278182,0.274864,0.000000,0.601187,...,45482.13,2673.69,6703.56,75653.93,85325.00,-2064.34,0.0,-2441.34,79135.32,3653.0
2,3,FY2019,0.193182,0.085227,0.301136,0.149148,0.271307,0.280134,0.026505,0.560063,...,47721.08,3476.71,7881.14,85206.58,99049.50,-2382.56,0.0,-2857.76,91180.43,4401.0
3,4,FY2020,0.256831,0.140255,0.273224,0.116576,0.213115,0.829405,0.099990,-0.002804,...,-79.18,2105.71,-33.10,28233.22,75855.75,-916.15,0.0,-1075.13,33974.47,4741.0
4,5,FY2021,0.177871,0.173669,0.242297,0.102241,0.303922,0.136685,0.095454,0.528763,...,22615.38,2056.50,8169.82,42770.39,57392.75,-1457.85,0.0,-1665.96,52660.44,4330.0
5,6,FY2022,0.204052,0.099855,0.312590,0.120116,0.263386,0.221614,0.016525,0.574506,...,44859.21,3703.11,10926.11,78083.04,89484.25,-2229.98,0.0,-2645.01,83304.26,4951.0
6,7,FY2023,0.209048,0.095164,0.319813,0.096724,0.279251,0.261732,0.025281,0.484349,...,42554.92,5129.68,14958.47,87860.02,99109.75,-2378.67,0.0,-2919.91,92041.17,4403.0
7,8,FY2024,0.197655,0.102178,0.340034,0.103853,0.256281,0.127612,0.041410,0.565386,...,45447.43,6991.29,14357.78,80383.08,89360.50,-2140.39,0.0,-2642.47,83307.64,3578.0
8,9,FY2025,0.240678,0.122034,0.330508,0.125424,0.181356,0.262672,0.040349,0.530843,...,57322.61,8486.19,9453.95,107984.18,119831.75,-3199.15,0.0,-3559.35,111893.25,3936.0
9,10,FY2026,0.207317,0.121951,0.315331,0.134146,0.221254,0.330618,0.059132,0.374889,...,28424.55,6089.53,11755.85,75821.22,84413.50,-2289.77,0.0,-2496.76,78436.97,3447.0
10,12,FY2027,0.663717,0.000000,0.000000,0.336283,0.000000,0.761212,0.000000,0.000000,...,0.00,3468.15,0.00,14523.95,15703.00,-431.73,0.0,-471.09,14800.18,672.0

In [161]:
# ledger has Fiscal_Year_id, alllocation_method_id 
# FY has Fiscal_Year_id, name
# Fetch example script from site
# Need to get FY, method_id, program_id, pct
#    method ID can be 21 and 22 (player and dollar)
#    program ID, 1 HS Fall, 2 HS Winter, 3 HS Spring, 5 MS Fall, 6 MS Spring
sample = pd.read_sql(""" 
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 1 as program_id,
program_registration_summary.hs_fall_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 2 as program_id,
program_registration_summary.winter_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 3 as program_id,
program_registration_summary.hs_spring_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 4 as program_id,
program_registration_summary.ms_fall_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 5 as program_id,
program_registration_summary.ms_spring_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 

SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 1 as program_id,
program_registration_summary.hs_fall_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 2 as program_id,
program_registration_summary.winter_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 3 as program_id,
program_registration_summary.hs_spring_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 5 as program_id,
program_registration_summary.ms_fall_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  
UNION ALL 
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 6 as program_id,
program_registration_summary.ms_spring_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy  


""", conn)
sample

DatabaseError: Execution failed on sql '
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 1 as program_id,
program_registration_summary.hs_fall_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 2 as program_id,
program_registration_summary.winter_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 3 as program_id,
program_registration_summary.hs_spring_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 4 as program_id,
program_registration_summary.ms_fall_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '21' as method_id, 5 as program_id,
program_registration_summary.ms_spring_player_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL

SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 1 as program_id,
program_registration_summary.hs_fall_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 2 as program_id,
program_registration_summary.winter_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 3 as program_id,
program_registration_summary.hs_spring_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 5 as program_id,
program_registration_summary.ms_fall_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy
UNION ALL
SELECT  fy.fiscal_year_id, fy.name, '22' as method_id, 6 as program_id,
program_registration_summary.ms_spring_dollar_pct as percentage
FROM fy left join program_registration_summary on fy.name = program_registration_summary.fy


': no such column: program_registration_summary.ms_fall_dollar_pct

In [158]:
# Fetch example script from site
sample = pd.read_sql(""" SELECT FY.fiscal_year_id, fy.name, allocation_rules.* 
FROM FY, allocation_rules where method_id in (1,2,3,4,5) """, conn)
sample

    fiscal_year_id    name  id  method_id  program_id  percentage
0                1  FY2017   1          1           1         1.0
1                2  FY2018   1          1           1         1.0
2                3  FY2019   1          1           1         1.0
3                4  FY2020   1          1           1         1.0
4                5  FY2021   1          1           1         1.0
5                6  FY2022   1          1           1         1.0
6                7  FY2023   1          1           1         1.0
7                8  FY2024   1          1           1         1.0
8                9  FY2025   1          1           1         1.0
9               10  FY2026   1          1           1         1.0
10              12  FY2027   1          1           1         1.0
11               1  FY2017   2          2           2         1.0
12               2  FY2018   2          2           2         1.0
13               3  FY2019   2          2           2         1.0
14               4  FY2020   2          2           2         1.0
15               5  FY2021   2          2           2         1.0
16               6  FY2022   2          2           2         1.0
17               7  FY2023   2          2           2         1.0
18               8  FY2024   2          2           2         1.0
19               9  FY2025   2          2           2         1.0
20              10  FY2026   2          2           2         1.0
21              12  FY2027   2          2           2         1.0
22               1  FY2017   3          3           3         1.0
23               2  FY2018   3          3           3         1.0
24               3  FY2019   3          3           3         1.0
25               4  FY2020   3          3           3         1.0
26               5  FY2021   3          3           3         1.0
27               6  FY2022   3          3           3         1.0
28               7  FY2023   3          3           3         1.0
29               8  FY2024   3          3           3         1.0
30               9  FY2025   3          3           3         1.0
31              10  FY2026   3          3           3         1.0
32              12  FY2027   3          3           3         1.0
33               1  FY2017   4          4           5         1.0
34               2  FY2018   4          4           5         1.0
35               3  FY2019   4          4           5         1.0
36               4  FY2020   4          4           5         1.0
37               5  FY2021   4          4           5         1.0
38               6  FY2022   4          4           5         1.0
39               7  FY2023   4          4           5         1.0
40               8  FY2024   4          4           5         1.0
41               9  FY2025   4          4           5         1.0
42              10  FY2026   4          4           5         1.0
43              12  FY2027   4          4           5         1.0
44               1  FY2017   5          5           6         1.0
45               2  FY2018   5          5           6         1.0
46               3  FY2019   5          5           6         1.0
47               4  FY2020   5          5           6         1.0
48               5  FY2021   5          5           6         1.0
49               6  FY2022   5          5           6         1.0
50               7  FY2023   5          5           6         1.0
51               8  FY2024   5          5           6         1.0
52               9  FY2025   5          5           6         1.0
53              10  FY2026   5          5           6         1.0
54              12  FY2027   5          5           6         1.0

In [ ]:

# Fetch example script from site
sample = pd.read_sql("""
with yearly_summary as (
            select
            /* For transactions, the Fiscal Year is from July 1 -> Jun 30 */
            strftime('%Y', date(topscore_transfer_items.transfer_timestamp, '+6 month', 'start of year')) as FY,
            
            /* Fall begins in July until December, Leverage the product mapping groupings
               Use the primary indicator to avoid the add-on registrations */
            count(distinct(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              and primary_registration_ind = 1
              then topscore_transfer_items.identifier
              else null end)) as hs_fall_players,
            count(distinct(case 
              when topscore_product_mappings.grouping = 'Winter' then topscore_transfer_items.identifier
              else null end)) as winter_players,
            count(distinct(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              and primary_registration_ind = 1
              then topscore_transfer_items.identifier
              else null end)) as hs_spring_players,
            count(distinct(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              and primary_registration_ind = 1
              then topscore_transfer_items.identifier
              else null end)) as ms_fall_players,
            count(distinct(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              and primary_registration_ind = 1
              then topscore_transfer_items.identifier
              else null end)) as ms_spring_players,


            count(distinct(topscore_transfer_items.identifier)) as reg_cnt,
            count(distinct(case 
                when topscore_product_mappings.primary_registration_ind = 1 
                then topscore_transfer_items.identifier
                else null end)) as primary_cnt, 

            /* For income, use total, not just primary registrations */
            sum(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              then topscore_transfer_items.amount
              else 0 end) as hs_fall_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'Winter' then topscore_transfer_items.amount
              else 0 end) as winter_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'High School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              then topscore_transfer_items.amount
              else 0 end) as hs_spring_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) > '06'
              then topscore_transfer_items.amount
              else 0 end) as ms_fall_dollars,
            sum(case 
              when topscore_product_mappings.grouping = 'Middle School' 
              and strftime('%m',date(topscore_transfer_items.transfer_timestamp)) <= '06'
              then topscore_transfer_items.amount
              else 0 end) as ms_spring_dollars,

            /* Summary income metrics */
            sum(case when item_type = 'payment'
              then topscore_transfer_items.amount else 0 end) as gross_amt,
            sum(case when item_type = 'cc_fee'
              then topscore_transfer_items.amount else 0 end) as credit_card_fees,
            sum(case when item_type = 'network_fee'
              then topscore_transfer_items.amount else 0 end) as network_fees,
            sum(case when item_type = 'topscore_fee'
              then topscore_transfer_items.amount else 0 end) as topscore_fees,
            sum(topscore_transfer_items.amount) as net_amt,
            count (*) as records
            from topscore_transfer_items
            left join topscore_product_mappings
            on topscore_transfer_items.product_name = topscore_product_mappings.product_name
            group by 1
            order by 1
)
select * 
from yearly_summary
        """, conn)
sample

In [62]:

# Fetch example script from site
sample = pd.read_sql("""

select * 
from allocation_methods left join allocation_rules 
 on allocation_methods.id = allocation_rules.method_id
 order by 1,2,3,4
 limit 20
        """, conn)
sample

,id,name,description,id,method_id,program_id,percentage
0,1,High School Fall,Direct entirely High School Fall,1,1,1,1.000000
1,2,High School Winter,Direct entirely High School Winter,2,2,2,1.000000
2,3,High School Spring,Direct entirely High School Spring,3,3,3,1.000000
3,4,Middle School Fall,Direct entirely Middle School Fall,4,4,5,1.000000
4,5,Middle School Spring,Direct entirely Middle School Spring,5,5,6,1.000000
...,...,...,...,...,...,...,...
72,20,Registration Distribution - 2027,Automatically calculated from TopScore registr...,1424,20,1,0.761212
73,20,Registration Distribution - 2027,Automatically calculated from TopScore registr...,1425,20,5,0.238788
74,20,Registration Distribution - 2027,Automatically calculated from TopScore registr...,1426,20,3,0.000000
75,20,Registration Distribution - 2027,Automatically calculated from TopScore registr...,1427,20,6,0.000000
76,20,Registration Distribution - 2027,Automatically calculated from TopScore registr...,1428,20,2,0.000000